name: Meore Workflow

on:
  workflow_dispatch:

jobs:
  multi-step:
    runs-on: ubuntu-latest
    steps:
      - name: Pirveli Nabiji
        run: echo "Es aris Pirveli Nabiji Rac Gaeshveba"

      - name: Meore Nabiji
        run: echo "Es aris Meore Nabiji Rac Gaeshveba"

      - name: Mesame Nabiji
        run: echo "Es aris Mesame Nabiji Rac Gaeshveba"
